WTW-IM/es-components

config/webpack.config.js
package.json
src/components/theme/index.js

Fix webpack configuration.
Update lint to run on src directory
Update babel compilation to run against src directory

Add theme for styled-components

---

src/components/base/containers/FormGroup.js
src/components/base/containers/FormGroup.md
src/components/base/containers/FormGroup.specs.js
src/components/base/containers/__snapshots__/FormGroup.specs.js.snap

Update FormGroup to use styled-components
Introduce snapshot tests for the FormGroup component

Update FormGroup component

---

package.json
src/components/base/containers/Alert.js
src/components/base/containers/Fieldset.md
src/components/base/containers/alert-variations.js
src/components/controls/Label.js
src/components/controls/radio-buttons/__snapshots__/RadioButton.specs.js.snap
src/components/controls/radio-buttons/__snapshots__/RadioGroup.specs.js.snap
src/components/controls/textbox/Addon.js
src/components/controls/textbox/Textbox.js
src/components/controls/textbox/Textbox.md
src/components/controls/textbox/Textbox.specs.js
src/components/controls/textbox/getAddonType.js
src/components/controls/textbox/getValidationStateVariables.js
src/components/theme/index.js
src/index.js

This pull request adds a Textbox component.
It includes updates to the theme to provide a common place for background colors that are used in different components.

Textbox component

---

package.json
src/components/controls/radio-buttons/RadioButton.specs.js
src/components/controls/radio-buttons/RadioGroup.js
src/components/controls/radio-buttons/RadioGroup.specs.js
src/components/controls/radio-buttons/__snapshots__/RadioButton.specs.js.snap
src/components/controls/radio-buttons/__snapshots__/RadioGroup.specs.js.snap
src/components/controls/textbox/Textbox.js
src/components/controls/textbox/Textbox.md

Fixes #20  
Textbox generated warning about switching from uncontrolled input to controlled input
RadioGroup shape object property name
Added:
Comment about autoFocus property on Textbox

Textbox and RadioGroup fix

---

docs/index.html
package.json
src/index.js

The DatePicker was being exported as ``Datepicker`` and should be exported as ``DatePicker``.

Fix datepicker export

---

package.json
src/components/containers/alert/Alert.js

Tweaks the margin on the leading and body text to properly line up with the leading header.

Alert Styling Fix

---

package.json
src/components/containers/alert/Alert.js
src/components/containers/alert/Alert.specs.js
styleguide.config.js

1. adjusted some Alert header styles:
a. bold text always has a line break before additional header text
b. text now flows to the right of the icon even on multiple lines
2. updated styleguide nav so containers section matches the folder structure

Alert tweaks

---

package.json
src/components/containers/drawer/Drawer.specs.js
src/components/containers/drawer/DrawerPanel.js
src/components/containers/drawer/__snapshots__/Drawer.specs.js.snap
src/components/containers/modal/Modal.md
src/components/containers/modal/ModalBody.js
src/components/containers/modal/ModalFooter.js
src/components/containers/popover/Popover.js
src/components/containers/popover/PopoverLink.js
src/components/containers/popover/__snapshots__/PopoverLink.specs.js.snap
src/components/controls/BaseControls.js
src/components/controls/textbox/Textbox.js
src/components/controls/textbox/Textbox.specs.js
src/components/util/Collapse.js

Made some changes to components to improve accessibility:
1. Updated Drawer component so headers are focus-able and keyboard navigable.
2. Added some aria attributes to drawer header/body.
3. Updated Textbox labels with explicit htmlFor attribute. Implicit labels only work when the label text is immediately followed by the input control so they weren't being recognized.
4. Added aria attribute to popoverlink and darkened value text. #29

Accessibility updates

---

package.json
src/components/navigation/sidenav/NavItem.js
src/components/navigation/sidenav/NavItem.md
src/components/navigation/sidenav/SideNav.js
src/components/navigation/sidenav/SideNav.md
src/components/navigation/sidenav/SideNav.specs.js
src/components/navigation/sidenav/__snapshots__/SideNav.specs.js.snap

SideNav Component:
1. Renamed some props in SideNav to be more standard (like onNavChange -> onChange) or for clarity (altStyle -> useAltStyle)
2. Converted SideNav and NavItem from classes to functions, removing state
3. Updated docs and samples for SideNav
4. Wrapped as uncontrollable component, now works controlled or uncontrolled

Sidenav refactor

---

package.json
src/components/containers/modal/Modal.js
src/components/containers/modal/Modal.md
src/components/containers/modal/ModalHeader.js
src/components/containers/modal/ModalHeader.specs.js
src/components/util/Fade.js

Cleaned up modal code, added more options and renamed some props.
Would like to figure out how to do the transitions without injecting classes (in Fade.js) but this works for now.

Modal cleanup

---

src/components/patterns/datepicker/DatePicker.js
src/components/patterns/datepicker/DatePicker.md
src/components/patterns/datepicker/datePickerStyles.js

1. adjusted some datepicker colors to pass WebAIM contrast test
2. fixed an import case issue (not sure how this got through initially, but it's causing probs for other PRs)
3. tweaked docs

Datepicker Color changes

---

.gitattributes
src/components/containers/popover/Popover.js
src/components/containers/popover/PopoverLink.js
src/components/containers/popover/__snapshots__/PopoverLink.specs.js.snap
src/components/controls/buttons/Button.js
src/components/controls/buttons/Button.md
src/components/controls/buttons/button-variants.js
src/components/controls/checkbox/Checkbox.js
src/components/patterns/datepicker/DatePicker.specs.js
src/components/util/ReactTextMask.js

Updated so the link button is more customizable, while maintaining the
backward compatibility for the existing users. There should be no change
if you don't use the new prop. Also added some lint ignores from jsx ally.

Update button and popover for styling

---

packages/es-components-via-theme/index.js

Mainly template strings aren't supported so I used concatenation (+). Also
it doesn't like properties to be defined as something else, it wants us to
explicitly assign values, i.e. color{black} should be color{black: black}

IE doesn't like some things about the theme

---

packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/containers/popover/Popover.js
packages/es-components/src/components/containers/popover/Popup.js
packages/es-components/src/components/containers/popover/__snapshots__/Popover.specs.js.snap

- Fixes bug where focus would jump back to previous popover when clicking something else with a mouse.
- Sets concrete font styling for popovers to prevent inheriting styles from parent components.

Minor Popover Updates

---

lerna.json
package-lock.json
package.json
packages/es-components-via-theme/index.js
packages/es-components-via-theme/package-lock.json
packages/es-components-via-theme/package.json
packages/es-components/README.md
packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/containers/notification/Notification.js
packages/es-components/src/components/containers/notification/Notification.md

Light and Message Notifications

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components/package.json
packages/es-components/src/index.js

I missed adding tabPanel to index.js so I can't import from downstream.

Tab panel include index

---

lerna.json
packages/es-components-via-theme/index.js
packages/es-components-via-theme/package.json
packages/es-components/package.json
packages/es-components/src/components/containers/tabPanels/Tab.js
packages/es-components/src/components/containers/tabPanels/TabPanel.js
packages/es-components/src/components/containers/tabPanels/TabPanel.md

Need to work with the tab panel to add classNames.

Updates to make the tab panel extendable

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components/package.json
packages/es-components/src/components/controls/textbox/Textbox.js
packages/es-components/src/components/controls/textbox/Textbox.md

Remove 25px right margin on InputWrapper used by TextBox

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components/package.json
packages/es-components/src/components/containers/tabPanels/TabPanel.js

This allows the consumer to decide what simple name should say.

Change JAWS to only read simple name

---

packages/es-components-wtw-theme/index.js
packages/es-components-wtw-theme/package-lock.json
packages/es-components-wtw-theme/package.json
packages/es-components/src/components/theme/Themes.md
publish-packages.sh

Team 5 required the WTW theme for an internal tool.

WTW Theme restored and updated

---

.gitignore
lerna.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/containers/notification/Notification.js
packages/es-components/src/components/containers/notification/Notification.md
packages/es-components/src/components/containers/popover/Popover.js
packages/es-components/src/components/containers/popover/__snapshots__/Popover.specs.js.snap

This PR fixes an issue with the Notificattion component when icons are included.

Fix notification icon

---

packages/es-components/src/components/containers/notification/Notification.js
packages/es-components/src/components/containers/notification/Notification.md
packages/es-components/src/components/containers/popover/Popover.js
packages/es-components/src/components/containers/popover/__snapshots__/Popover.specs.js.snap

1) Fixed link color issue with new notification backgrounds
2) Moved CTAs inside the light variant notifications as per [UX guide](http://prototypes-wtw.net/containers/#alerts)

Notification Link & CTA Update

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/package.json
packages/es-components/src/components/containers/tabPanels/Tab.js
packages/es-components/src/components/containers/tabPanels/TabPanel.js
packages/es-components/src/components/containers/tabPanels/TabPanel.md

Minor tweaks to help JAWS to read what needs to be read. The biggest change is the tab panels takes in what needs to be read from the parent.

Tab panel jaws subtext

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/package.json
packages/es-components/src/components/containers/striped-container/StripedContainer.js
packages/es-components/src/components/containers/striped-container/StripedContainer.md

Add a new component for rendering a set of children in alternating striped colors.

Add StripedContainer container component

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/README.md
packages/es-components/package.json
packages/es-components/webpack-components-bundle.config.js

This PR also includes some updates to the Webpack config to use the correct global variables for React and Styled Components.

UMD Example Usage

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/package.json
packages/es-components/src/components/patterns/datepicker/DatePicker.js
packages/es-components/src/components/patterns/datepicker/DatePicker.md

Adding the validationState prop and passing it through to the TextBox.  
Adding validation examples to the Example.

Adding validationState to Datepicker

---

lerna.json
packages/es-components-via-theme/index.js
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/controls/textbox/Textbox.js
packages/es-components/src/components/patterns/datepicker/DatePicker.js
packages/es-components/src/components/patterns/datepicker/datePickerStyles.js

- Updates Textbox component to match the latest [UX toolkit](http://prototypes-wtw.net/controls/?#forms-control-validation).
- Updated datepicker to display the calendar icon on the left side of the input.
- Updated Prettier.

Textbox style update

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/containers/tabPanels/Tab.js
packages/es-components/src/components/containers/tabPanels/TabPanel.js

Just a bit of clean up and tweaks for TabPanels. Mostly helps with a small duplicate key issue in ui-components.

Minor tweaks to tabpanels

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/package.json
packages/es-components/src/components/patterns/screenReaderOnly/screenReaderOnly.js
packages/es-components/src/components/patterns/screenReaderOnly/screenReaderOnly.md
packages/es-components/src/index.js

Create screenReaderOnly HoC

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/.npmignore
packages/es-components/package.json
packages/es-components/src/components/containers/modal/Modal.js
packages/es-components/src/components/containers/notification/Notification.js
packages/es-components/src/components/containers/tabPanels/Tab.js
packages/es-components/src/components/containers/tooltip/Tooltip.js
packages/es-components/src/components/controls/buttons/ToggleButton.js
packages/es-components/src/components/controls/checkbox/Checkbox.js
packages/es-components/src/components/controls/dropdown/Dropdown.js
packages/es-components/src/components/controls/radio-buttons/RadioButton.js
packages/es-components/src/components/controls/textbox/Textbox.js
packages/es-components/src/components/patterns/datepicker/DatePicker.js
packages/es-components/src/components/patterns/incrementer/Incrementer.js

Babel 7 Fallout

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/base/spinner/Spinner.js
packages/es-components/src/components/base/spinner/Spinner.md
packages/es-components/src/index.js

This branch is currently based off of #200. If we want to merge it before that PR, it can be rebased as needed.

[WIP] - Spinner Component

---

lerna.json
package-lock.json
package.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/package.json
packages/es-components/src/components/containers/drawer/Drawer.js
packages/es-components/src/components/controls/textbox/Textbox.js
packages/es-components/src/components/controls/textbox/Textbox.specs.js
packages/es-components/src/components/controls/textbox/__snapshots__/Textbox.specs.js.snap

1) Fixed an issue with Textbox where the default value for `defaultValue` was causing it to be added to textbox in situations where it was not desired (i.e. value/onchange were supplied).  Added a test to check this.
2) Fixed a style issue with Textbox label weight.
3) Updated Drawer's defaultActiveKeys to prevent a similar issue as 1.
4) Updated a couple of dependency versions to resolve a security issue.

Textbox Fix

---

lerna.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/package.json
packages/es-components/CHANGELOG.md
packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/containers/fieldset/Fieldset.js
packages/es-components/src/components/controls/checkbox/Checkbox.js
packages/es-components/src/components/controls/checkbox/Checkbox.md
packages/es-components/src/components/controls/checkbox/Checkbox.specs.js
packages/es-components/src/components/controls/checkbox/__snapshots__/Checkbox.specs.js.snap
packages/es-components/src/components/controls/dropdown/Dropdown.js
packages/es-components/src/components/controls/dropdown/Dropdown.md
packages/es-components/src/components/controls/radio-buttons/RadioButton.js
packages/es-components/src/components/controls/radio-buttons/RadioButton.specs.js
packages/es-components/src/components/controls/radio-buttons/RadioGroup.js
packages/es-components/src/components/controls/radio-buttons/RadioGroup.md
packages/es-components/src/components/controls/radio-buttons/RadioGroup.specs.js
packages/es-components/src/components/controls/radio-buttons/__snapshots__/RadioButton.specs.js.snap
packages/es-components/src/components/controls/radio-buttons/__snapshots__/RadioGroup.specs.js.snap
packages/es-components/src/components/controls/radio-buttons/radio-fill-variables.js
packages/es-components/src/components/controls/textbox/Textbox.js
packages/es-components/src/components/controls/textbox/Textbox.specs.js

This PR fixes the styling of the RadioGroup 
- No more underline of the legend
- Updating the label font-size to be smaller
- Stacking the radio buttons for the mobile breakpoint
- Updating a few instances of padding/margins to be consistent with the VB UI Toolkit
Implements consistent validation behavior with TextBox:
- Updates Checkbox to accept `validationState` and `additionalHelpContent`
- Updates RadioGroup to accept `validationState` and `additionalHelpContent` and removes `hasError`
- Updates Dropdown to accept `additionalHelpContent`

Adding ValidationState and AdditionalHelpContent to RadioGroup and Checkbox

---

packages/es-components/src/components/containers/menu/MenuPanel.js
packages/es-components/src/components/containers/menu/MenuSection.js
packages/es-components/src/components/controls/buttons/ToggleButton.js

If @Darrken's button pr gets merged first it's pretty easy to rebase my `ToggleButton` changes on top.

Minor Menu Fixes

---

packages/es-components/src/components/containers/modal/Modal.md
packages/es-components/src/components/containers/notification/Notification.md

I noticed a few console errors running the `next` branch, one caused by a merge conflict that hadn't been resolved. This addresses those.

Fix for a merge conflict

---

packages/es-components-via-theme/index.js
packages/es-components-wtw-theme/index.js
packages/es-components/src/components/containers/notification/useNotification.js
packages/es-components/src/components/controls/textbox/Textbox.js

UX wants to use slightly different success/error icons.

Success & Error Icons

---

packages/es-components/package-lock.json
packages/es-components/src/components/containers/tooltip/Tooltip.js
packages/es-components/src/components/containers/tooltip/Tooltip.specs.js

`aria-describedby` has to refer to an element that exists on the DOM. The Tooltip Overlay is not on the DOM, so I've added a `screenReaderOnly` element to act as the descriptor.

Update: using a static element to describe Tooltips

---

packages/es-components/package-lock.json
packages/es-components/src/components/controls/answer-group/AnswerButton.js
packages/es-components/src/components/controls/answer-group/AnswerGroup.js
packages/es-components/src/components/controls/answer-group/AnswerGroup.md
packages/es-components/src/index.js

AnswerGroup Component

---

README.md
package-lock.json
packages/es-components/package-lock.json
packages/es-components/src/components/navigation/horizontalnav/HorizontalNav.md
packages/es-components/src/components/navigation/horizontalnav/__snapshots__/HorizontalNav.specs.js.snap
packages/es-components/src/components/navigation/useNavigationItem.js

I don't know why I didn't do it this way before. 🙃

Simplify nav children

---

packages/es-components/src/components/controls/answer-group/AnswerButton.js
packages/es-components/src/components/controls/answer-group/AnswerGroup.md
packages/es-components/src/components/controls/label/Label.js

Also fixed a small width issue on mobile with `Label`.

Update: add validationState to AnswerGroup

---

packages/es-components/src/index.js

This pull request exposes the fade component from utils.

New: expose Fade component

---

packages/es-components/src/components/controls/dropdown/Dropdown.js
packages/es-components/src/components/controls/textbox/InputText.js
packages/es-components/src/components/controls/textbox/TextAddons.js
packages/es-components/src/components/patterns/dateInput/DateInput.js
packages/es-components/src/components/patterns/dateInput/DateInput.md
packages/es-components/src/components/patterns/dateInput/DateInput.specs.js
packages/es-components/src/components/patterns/dateInput/Day.js
packages/es-components/src/components/patterns/dateInput/Month.js
packages/es-components/src/components/patterns/dateInput/Year.js
packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap
packages/es-components/src/index.js

New: dateInput component

---

packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/containers/drawer/Drawer.js
packages/es-components/src/components/containers/drawer/DrawerContext.js
packages/es-components/src/components/containers/drawer/DrawerPanel.js
packages/es-components/src/components/containers/fieldset/Fieldset.js
packages/es-components/src/components/containers/modal/Modal.js
packages/es-components/src/components/containers/modal/ModalHeader.js
packages/es-components/src/components/containers/popover/Popover.md
packages/es-components/src/components/containers/tabPanels/Tab.js
packages/es-components/src/components/containers/tabPanels/TabPanel.js
packages/es-components/src/components/containers/tabPanels/TabPanel.md
packages/es-components/src/components/containers/tooltip/Tooltip.js
packages/es-components/src/components/controls/Control.js
packages/es-components/src/components/controls/answer-group/AnswerGroup.js
packages/es-components/src/components/controls/buttons/Button.js
packages/es-components/src/components/controls/buttons/Button.md
packages/es-components/src/components/controls/buttons/OutlineButton.js
packages/es-components/src/components/controls/buttons/OutlineButton.md
packages/es-components/src/components/controls/buttons/PopoverLink.js
packages/es-components/src/components/controls/dropdown/Dropdown.js
packages/es-components/src/components/controls/textbox/InputText.js
packages/es-components/src/components/patterns/dateInput/Month.js
packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap
packages/es-components/src/components/patterns/incrementer/Incrementer.js
packages/es-components/src/components/util/StyleReset.js

- A handful of style updates based on UX team feedback and BDA toolkit.
- Some code cleanup in Modal, Drawer, and TabPanel for readability/accessibility.
- Button and OutlineButton min-width is 100px. AnswerButton default is 100px up from 75px.
- Font family added to Tooltip and Modal.
- Control was updated to use mobile-first media queries, fixing some downstream issues.

Style updates

---

packages/es-components/src/components/controls/dropdown/Dropdown.js
packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap

Fixed a single css prop to allow dropdown to be full width again.

Fix: dropdown not full width

---

packages/es-components/src/components/controls/dropdown/Dropdown.js
packages/es-components/src/components/controls/textbox/TextAddons.js
packages/es-components/src/components/patterns/dateInput/DateInput.js
packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap
packages/es-components/src/components/util/StyleReset.js

- fixes DateInput day issue
- adjusted UL/LI default styles a bit
- fixed a safari issue with textbox append/prepends
- set min-width on Dropdown to avoid some text/icon overlap

Fix: DateInput allows 0x for days

---

packages/es-components/src/components/containers/notification/useNotification.js
packages/es-components/src/components/navigation/horizontalnav/HorizontalNav.md
packages/es-components/src/components/navigation/sidenav/SideNav.md
packages/es-components/src/components/patterns/dateInput/DateInput.js
packages/es-components/src/components/patterns/dateInput/Day.js
packages/es-components/src/components/patterns/dateInput/Month.js
packages/es-components/src/components/patterns/dateInput/Year.js
packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap

Fixes some width issues with DateInput when resizing in smaller containers/screen widths.

Fix: dateinput widths in mobile/desktop

---

packages/es-components/src/components/controls/buttons/ActionButton.js
packages/es-components/src/components/controls/buttons/ActionButton.md
packages/es-components/src/components/controls/buttons/Button.js
packages/es-components/src/components/controls/buttons/LinkButton.js
packages/es-components/src/components/controls/buttons/LinkButton.md
packages/es-components/src/components/controls/buttons/OutlineButton.js
packages/es-components/src/components/controls/buttons/OutlineButton.md

Based on Tim's semantic hover button prototype. This button uses the default color style, and changes its hover color based on the styleType.

New: actionButton component

---

packages/es-components/src/components/controls/textbox/TextAddons.js
packages/es-components/src/components/controls/textbox/Textarea.js
packages/es-components/src/components/controls/textbox/Textarea.md
packages/es-components/src/components/controls/textbox/Textbox.js
packages/es-components/src/components/controls/textbox/Textbox.md
packages/es-components/src/index.js

New: Textarea component

---

packages/es-components/src/components/controls/answer-group/AnswerButton.js
packages/es-components/src/components/controls/answer-group/AnswerGroup.md
packages/es-components/src/components/controls/checkbox/Checkbox.js
packages/es-components/src/components/controls/radio-buttons/RadioButton.js
packages/es-components/src/components/controls/radio-buttons/RadioGroup.md
packages/es-components/src/components/controls/textbox/Textbox.js
packages/es-components/src/components/util/isValidEmail.js
packages/es-components/src/index.js

Some mostly minor updates to validation styles, so text remains default colors.
AnswerButton would probably benefit from being split into two different components (regular and outline variants), but I'm avoiding a breaking change at the moment. Unless anyone feels strongly about just splitting it up now.

Validation updates

---

package-lock.json
packages/es-components/src/components/patterns/datepicker/DatePicker.js
packages/es-components/src/components/patterns/datepicker/DatePicker.md

Adds a prop to allow downstream users to suppress the datepicker on desktop and android devices.

Update: adds ability to suppress datepicker with prop

---

packages/es-components/src/components/base/spinner/Spinner.js

Adds a stripped-down version of the spinner for IE11. Reviewed by UX.

Fix: IE11 spinner

---

package-lock.json
packages/es-components/package-lock.json
packages/es-components/src/components/controls/buttons/DropdownButton.js
packages/es-components/src/components/controls/buttons/DropdownButton.md

Add an inline prop to the DropdownButton component that allows it to be rendered inline.

Update: allow inline DropdownButton components

---

packages/es-components/src/components/patterns/dateInput/DateInput.js

Fixes a very small issue in DateInput where it clears itself and causes validation issues downstream.

Update: fixes dateInput clearing itself

---

packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/containers/sliding-pane/SlidingPane.js
packages/es-components/src/components/containers/sliding-pane/SlidingPane.md
packages/es-components/src/components/containers/sliding-pane/SlidingPaneStyles.js

This was copied, with little modification, from one of our internal repos.

New: moving the SlidingPane component from internal repo

---

packages/es-components/package-lock.json
packages/es-components/src/components/containers/sliding-pane/SlidingPane.js
packages/es-components/src/components/containers/sliding-pane/SlidingPane.md
packages/es-components/src/components/containers/sliding-pane/SlidingPaneStyles.js
packages/es-components/src/index.js

- moved most styling out of createGlobalStyle call
- added export to index.js

SlidingPane style updates

---

packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/patterns/progress-tracker/ProgressTracker.js
packages/es-components/src/components/patterns/progress-tracker/ProgressTracker.md
packages/es-components/src/components/patterns/progress-tracker/ProgressTracker.specs.js
packages/es-components/src/components/patterns/progress-tracker/__snapshots__/ProgressTracker.specs.js.snap
packages/es-components/src/components/patterns/progress-tracker/progress-tracker-subcomponents.js
packages/es-components/src/components/patterns/progress-tracker/progress-tracker-subcomponents.specs.js
packages/es-components/src/components/patterns/progress-tracker/pt-sizes.js
packages/es-components/src/index.js

Adding the progress tracker so it can be used in other applications.

New: add progress tracker

---

packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/controls/checkbox/CheckAllBox.js
packages/es-components/src/components/controls/checkbox/Checkbox.js
packages/es-components/src/components/controls/checkbox/CheckboxGroup.js
packages/es-components/src/components/controls/checkbox/CheckboxGroup.md
packages/es-components/src/components/controls/checkbox/CheckboxGroup.specs.js
packages/es-components/src/index.js

New: CheckboxGroup

---

packages/es-components/package-lock.json
packages/es-components/src/components/containers/fieldset/Fieldset.md
packages/es-components/src/components/controls/buttons/DropdownButton.js
packages/es-components/src/components/controls/textbox/MaskedTextbox.md
packages/es-components/src/components/controls/textbox/Textbox.md
packages/es-components/src/components/navigation/horizontalnav/__snapshots__/HorizontalNav.specs.js.snap
packages/es-components/src/components/navigation/useNavigationItem.js
packages/es-components/src/components/patterns/starRating/StarRating.js
packages/es-components/src/components/patterns/starRating/StarRatingExplanation.js
packages/es-components/src/components/util/RootCloseWrapper.js

- Fixed DropdownButton inline functionality
- Fixed formatMessage warnings
- Fixed SideNav isVertical prop from passing through to children
- Moved padding from SideNav li to nav item (don't think this is a breaking change but I can remove this if it is)

Sidenav padding and general warning updates

---

packages/es-components/src/components/navigation/Anchor.js
packages/es-components/src/components/navigation/Anchor.md
packages/es-components/src/index.js

New: anchor component

---

package-lock.json
packages/es-components/package-lock.json

- Merged in bot PRs for lodash and acorn
- auto audit of dependencies

Dependency audit

---

packages/es-components-via-theme/index.js
packages/es-components-wtw-theme/index.js
packages/es-components/src/components/containers/prompt/Prompt.js
packages/es-components/src/components/containers/prompt/Prompt.md
packages/es-components/src/components/containers/prompt/Prompt.specs.js
packages/es-components/src/components/containers/prompt/PromptType.js
packages/es-components/src/index.js

Prompt for agent read aloud text and agent do not read aloud text.

New: prompt for read aloud and do not read aloud text. (refs TW-56968)

---

packages/es-components/src/components/controls/radio-buttons/RadioButton.js
packages/es-components/src/components/controls/radio-buttons/RadioGroup.js

#408 introduce some warning messages in development

Fix: Remove warnings about controlled and uncontrolled inputs for radio buttons

---

packages/es-components/src/components/containers/popover/Popover.js
packages/es-components/src/components/containers/popover/Popup.js

Add parentNode to set the node with which to create the React portal.

Update: add parentNode prop to Popover

---

packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/controls/buttons/DropdownButton.js
packages/es-components/src/components/patterns/dateInput/DateInput.js
packages/es-components/src/components/util/useRootNode.js
packages/es-components/styleguide.config.js

This polyfill only takes effect when `getRootNode` does not already exist on the `Node` prototype.

Polyfilling getRootNode

---

packages/es-components/src/components/controls/buttons/IconButton.js
packages/es-components/src/components/controls/buttons/IconButton.md

Restructured the IconButton component to use the OutlineButton as a basis so we get those hover/active/focus states for free. Reviewed by UX (Dave, Keoni).

Update: style changes to IconButton

---

packages/es-components/src/components/containers/notification/LightNotification.js
packages/es-components/src/components/containers/notification/MessageNotification.js
packages/es-components/src/components/containers/notification/Notification.js
packages/es-components/src/components/containers/notification/Notification.md
packages/es-components/src/components/containers/notification/useNotification.js

Allows for notifications to show the icon at all screen resolutions

Update: Adding optional alwaysShowIcon to notification

---

packages/es-components/src/components/containers/modal/Modal.md
packages/es-components/src/components/containers/tabPanels/TabPanel.md
packages/es-components/src/components/patterns/progress-tracker/ProgressTracker.md

- can't open a Modal (https://wtw-im.github.io/es-components/#!/Modal)
- clickable ProgressTracker isn't even rendered (https://wtw-im.github.io/es-components/#!/ProgressTracker)
- 2nd TabPanel missing default selection (https://wtw-im.github.io/es-components/#!/TabPanel)

Fix: address state issues in some component's md files

---

packages/es-components/src/components/controls/radio-buttons/RadioButton.js
packages/es-components/src/components/controls/radio-buttons/RadioGroup.md

Simple update which adds `className` to `RadioButton`, allowing styled-component usage and some additional flexibility.

Update: added className prop to RadioButton

---

packages/es-components/src/components/patterns/dateInput/Day.js
packages/es-components/src/components/patterns/dateInput/Year.js
packages/es-components/src/components/patterns/dateInput/onNonNumericHandler.js

Fix: prevent non-numeric input for Day and Year

---

packages/es-components/package-lock.json
packages/es-components/src/components/controls/buttons/PopoverLink.js
packages/es-components/src/components/patterns/statusTracker/StatusTracker.js
packages/es-components/src/components/patterns/statusTracker/StatusTracker.md
packages/es-components/src/components/patterns/statusTracker/StatusTracker.specs.js
packages/es-components/src/components/patterns/statusTracker/__snapshots__/StatusTracker.specs.js.snap
packages/es-components/src/index.js

New: statusTracker component

---

packages/es-components/src/components/containers/drawer/DrawerPanel.js

I'd like to have ability to focus the header of Drawer panel.

Update: expose ref for Drawer header button

---

packages/es-components/src/components/patterns/starRating/StarRating.js

WE-10824 added customized noRatingText prop

Update: added custom No Rating text via prop

---

packages/es-components/src/components/containers/horizontalScrollWrapper/HorizontalScrollWrapper.js
packages/es-components/src/components/containers/horizontalScrollWrapper/HorizontalScrollWrapper.md
packages/es-components/src/components/controls/buttons/IconButton.js

Worked with @jddev27 on these changes.

Update: correcting accessibility on IconButton and HorizontalScrollWrapper buttons

---

packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/patterns/datepicker/DatePicker.md
packages/es-components/src/components/patterns/datepicker/datePickerStyles.js

Updated to newest version of react-datepicker, which improves some accessibility features (like being able to use keyboard when using the `inline` prop).

Update: newest react-datepicker, updated styles

---

packages/es-components-via-theme/package-lock.json
packages/es-components-wtw-theme/package-lock.json
packages/es-components/package-lock.json
packages/es-components/src/components/general-styling-guidelines/GeneralStylingGuidelines.md
packages/es-components/styleguide.config.js

This is just a start, and we can expand on this if we want. I just had on my list to write this down _somewhere_. 😆

Adding some General Styling Guidelines

---

packages/es-components/src/components/containers/popover/Popover.js
packages/es-components/src/components/containers/popover/Popup.js
packages/es-components/src/components/containers/sliding-pane/SlidingPane.js

Also add prop for popover for popper keepTogether

Update: allow sliding pane to hide header

---

packages/es-components/config/import-matchers.js
packages/es-components/package-lock.json
packages/es-components/src/components/containers/heading/Heading.js
packages/es-components/src/components/containers/heading/Heading.md
packages/es-components/src/components/containers/heading/Heading.specs.js
packages/es-components/src/components/containers/heading/__snapshots__/Heading.specs.js.snap
packages/es-components/src/components/containers/modal/__snapshots__/Modal.specs.js.snap
packages/es-components/src/components/navigation/breadcrumb/__snapshots__/Breadcrumb.specs.js.snap
packages/es-components/src/components/navigation/horizontalnav/__snapshots__/HorizontalNav.specs.js.snap
packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap
packages/es-components/src/components/patterns/progress-tracker/__snapshots__/ProgressTracker.specs.js.snap
packages/es-components/src/components/patterns/statusTracker/__snapshots__/StatusTracker.specs.js.snap

This was previously written with some faulty expectations about `attr` processing order, but it works now! (And there is a test for it!)

Correcting attr Usage in Headings

---

CHANGELOG.md
lerna.json
packages/es-components-via-theme/CHANGELOG.md
packages/es-components-via-theme/package-lock.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/CHANGELOG.md
packages/es-components-wtw-theme/package-lock.json
packages/es-components-wtw-theme/package.json
packages/es-components/CHANGELOG.md
packages/es-components/package-lock.json
packages/es-components/package.json

This change didn't end up resolving @Celestios's issue, but it also caused no issues. I figure an extra null check can't hurt!

Merge Pre-Prod to Master

---

packages/es-components/src/components/containers/fieldset/Fieldset.md
packages/es-components/src/components/containers/notification/LightNotification.md
packages/es-components/src/components/containers/notification/Notification.md
packages/es-components/src/components/controls/Controls.md
packages/es-components/src/components/controls/checkbox/Checkbox.md
packages/es-components/src/components/controls/checkbox/CheckboxGroup.md
packages/es-components/src/components/controls/dropdown/Dropdown.md
packages/es-components/src/components/controls/radio-buttons/RadioGroup.md
packages/es-components/src/components/controls/textbox/Textarea.md
packages/es-components/src/components/controls/textbox/Textbox.md
packages/es-components/src/components/patterns/dateInput/DateInput.md
packages/es-components/src/components/patterns/datepicker/DatePicker.md
packages/es-components/src/components/validation-guidelines/ValidationGuidelines.md
packages/es-components/styleguide.config.js

New Validation Guidelines section and links to UX patterns.

Docs: include links to UX validation patterns

---

packages/es-components-wtw-theme/index.js

Updates Warning/Danger icons to match BDA design specs

Fix: corrects wtw theme danger/warning icons.

---

.github/workflows/ci.yml
package-lock.json
package.json
packages/es-components/src/components/containers/drawer/Drawer.md
packages/es-components/src/components/containers/drawer/DrawerItem.js

Also updating CI to run the pre-prod update _after_ the main update, rather than before.

Adding onChange to Drawer.Item

---

CHANGELOG.md
lerna.json
packages/es-components-via-theme/CHANGELOG.md
packages/es-components-via-theme/index.js
packages/es-components-via-theme/package-lock.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/CHANGELOG.md
packages/es-components-wtw-theme/package-lock.json
packages/es-components-wtw-theme/package.json
packages/es-components/CHANGELOG.md
packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/controls/textbox/InputBase.js
packages/es-components/src/components/controls/textbox/Textarea.js
packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap

Adding baseFontFace - pre-prod -> main

---

CHANGELOG.md
lerna.json
packages/es-components-via-theme/CHANGELOG.md
packages/es-components-via-theme/package-lock.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/CHANGELOG.md
packages/es-components-wtw-theme/package-lock.json
packages/es-components-wtw-theme/package.json
packages/es-components/CHANGELOG.md
packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/containers/fieldset/Fieldset.js
packages/es-components/src/index.js

See #629 and #631 for more details.

Pre-Prod -> Main - Exporting useUniqueId

---

CHANGELOG.md
lerna.json
packages/es-components-via-theme/CHANGELOG.md
packages/es-components-via-theme/package-lock.json
packages/es-components-via-theme/package.json
packages/es-components-wtw-theme/CHANGELOG.md
packages/es-components-wtw-theme/package-lock.json
packages/es-components-wtw-theme/package.json
packages/es-components/CHANGELOG.md
packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/full-color-icons.js

Pre-Prod -> Main - Full Color Icons Fix

---

.github/workflows/ci.yml

Updating for main. This _should_ get merged back to pre-prod if everything's working correctly.

Build: only running lint on feature branches

---

packages/es-components-via-theme/index.js
packages/es-components-wtw-theme/index.js

Update: added blue25 to themes

---

packages/es-components-via-theme/index.js
packages/es-components-wtw-theme/index.js
packages/es-components/src/components/containers/banner/Banner.js
packages/es-components/src/components/containers/banner/Banner.md
packages/es-components/src/components/containers/banner/Banner.specs.js
packages/es-components/src/index.js

We created a new component as a container which allows background color and color properties

New: Banner es-component

---

.github/workflows/ci.yml
.github/workflows/preprod-ci.yml
.gitignore
package-lock.json
packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/rollup.config.js
packages/es-components/styleguide.config.js

Also:
* Fixing potential issues with publishes
* Adding CHANGELOG to Docs

Build: not pushing changes to docs if none

---

packages/es-components/package-lock.json
packages/es-components/src/components/controls/textbox/InputBase.js
packages/es-components/src/components/controls/textbox/Textarea.js
packages/es-components/src/components/controls/textbox/__snapshots__/Textbox.specs.js.snap
packages/es-components/src/components/patterns/datepicker/DatePicker.js
packages/es-components/src/components/patterns/datepicker/DatePicker.md
packages/es-components/src/components/patterns/datepicker/datePickerStyles.js
packages/es-components/src/components/patterns/datepicker/datepickerAssets.js

Removing Datepicker Input Width Limits

---

CHANGELOG.md
lerna.json
packages/es-components/.eslintrc.js
packages/es-components/CHANGELOG.md
packages/es-components/package-lock.json
packages/es-components/package.json
packages/es-components/src/components/containers/drawer/Drawer.specs.js
packages/es-components/src/components/controls/buttons/OutlineButton.js

Fix: ensuring all @babel/runtime dependencies are not devDependencies

Pre-Prod -> Main - 05/09/2023 (2)

---

packages/es-components/src/components/containers/notification/BaseNotification.tsx
packages/es-components/src/components/controls/checkbox/CheckboxGroup.md
packages/es-components/src/components/controls/radio-buttons/RadioGroup.md

Borken (before):
Fixed (after):

Fix: fixing Notification anchor and button colors

---

packages/es-components/src/components/grid/Grid.md

EN-19668: update docs adding new v5 grid and utils

---

packages/es-components/src/components/containers/popover/Popover.md
packages/es-components/src/components/containers/tooltip/Tooltip.md
packages/es-components/src/components/util/Fade.tsx
packages/es-components/src/components/util/callRef.ts

This includes changes from #810.

Clearing console warnings around Fade

---

packages/es-components/src/components/containers/modal/ModalHeader.tsx
shared/types/src/ESTheme.ts

Currently the size of the header cannot be changed.

ENIFP-3285: Allow Modal Header Size Alteration

---

.github/workflows/canary-publish.yml
packages/es-components/src/components/controls/buttons/OutlineButton.md
packages/es-components/src/components/controls/buttons/OutlineButton.tsx

Fix: changing outline button to a styled component of button

---

packages/es-components/src/components/controls/buttons/OutlineButton.tsx

Fix: overflow in outlinebutton

---

packages/es-components/src/components/controls/buttons/OutlineButton.tsx

EN-22665 Fix: button styles to keep format as an anchor
