- package.json
This adds the following new packages:
[prettier](https://github.com/prettier/prettier)
[lint-staged](https://github.com/okonet/lint-staged)
[husky](https://github.com/typicode/husky)
When you commit your files, it will prettify only the staged .js files and then run eslint --fix on them.  I haven't versioned this or prettified the whole project with this commit because I'm sure there will be opinions/feedback on this.  Maybe we don't want to auto fix lint issues, etc.
I also added a "prettify" npm script that will parse the whole project, mostly as reference, but also in case we decide to change any settings later it might be useful.
> Prettier with pre-commit hook

- package.json
- src/components/containers/alert/Alert.js
This pull request fixes a few minor issues that have been discovered upon their usage:
1. Icons were not rendering properly for ``warning`` and ``danger`` alert types. 
2. PropTypes were too restrictive for designs
3. No props were propagated making it difficult to add additional attributes to the wrapping div in the Alert component (e.g. ids)
> Update Alert component

- src/components/patterns/incrementer/Incrementer.js
I forgot to set the ``value`` field on the state object when new props are received. This PR makes sure that ``value`` gets set on the state in addition to the ``incrementButtonDisabled`` and ``decrementButtonDisabled`` values.
> Fix componentWillReceiveProps

- src/components/base/icons/Icon.md
- src/components/containers/drawer/Drawer.md
- src/components/containers/fieldset/Fieldset.md
- src/components/containers/modal/Modal.md
- src/components/containers/notification/Notification.md
- src/components/containers/tooltip/Tooltip.md
- src/components/controls/buttons/Button.md
- src/components/controls/datepicker/DatePicker.md
- src/components/controls/dropdown/Dropdown.md
- src/components/controls/radio-buttons/RadioGroup.md
- src/components/controls/textbox/Textbox.md
- src/components/navigation/sidenav/SideNav.md
- src/components/patterns/datepicker-textbox/DatePickerTextbox.md
- src/components/patterns/incrementer/Incrementer.md
Simple change to make markdown in docs consistent.  Inline code text only requires a single backtick.
> Fixed mixed usage of backticks

- package.json
- src/components/containers/drawer/Drawer.js
- src/components/containers/drawer/Drawer.md
- src/components/containers/drawer/Drawer.specs.js
- src/components/containers/drawer/DrawerPanel.js
- src/components/containers/drawer/DrawerPanel.md
- src/components/containers/drawer/__snapshots__/Drawer.specs.js.snap
Drawer Component:
1. Added onActiveKeysChanged callback, removed defaultActiveKeys prop
2. Converted Drawer from class to function, removed state
3. Renamed Drawer prop isActive -> isOpen
4. Wrapped as uncontrollable component, now works controlled or uncontrolled
5. Updated docs to include both controlled and uncontrolled examples
> Drawer refactor

- lerna.json
- packages/es-components-via-theme/package.json
- packages/es-components/package.json
- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/containers/popover/__snapshots__/Popover.specs.js.snap
- packages/es-components/src/components/controls/checkbox/Checkbox.js
- packages/es-components/src/components/controls/checkbox/__snapshots__/Checkbox.specs.js.snap
Adds an ariaLabel prop on Checkbox because screen readers were not picking up aria-labels when put on the Checkbox.
Adds more descriptive close instructions to Popover that will receive focus on popovers without close buttons. This still allows the popovers to be properly read without the title being read twice, and gives better instruction on how to close the popover.
> Minor accessibility fixes for Checkbox and Popovers

- lerna.json
- packages/es-components-via-theme/package.json
- packages/es-components-wtw-theme/package.json
- packages/es-components/package.json
- packages/es-components/src/components/patterns/datepicker/DatePicker.js
This library has a peerDependency of React >= 0.14. Because of this, PureComponent causes issues in any app using a version of React that does not support PureComponent. Until those applications can be updated, this library cannot use PureComponent.
> Remove purecomponent

- lerna.json
- packages/es-components-via-theme/package.json
- packages/es-components-wtw-theme/package.json
- packages/es-components/package.json
- packages/es-components/src/components/controls/buttons/DropdownButton.js
There are two props for setting the value in a DropDownButton component. It no longer needs the buttonValue prop to be required.
> Remove required prop from dropdownbutton

- lerna.json
- packages/es-components-via-theme/package.json
- packages/es-components-wtw-theme/package.json
- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/containers/popover/Popover.md
- packages/es-components/src/components/containers/popover/Popover.specs.js
- packages/es-components/src/components/containers/popover/Popup.js
- packages/es-components/src/components/containers/popover/__snapshots__/Popover.specs.js.snap
- packages/es-components/src/components/containers/popover/popoverStyles.js
- packages/es-components/src/components/containers/tooltip/Tooltip.js
- packages/es-components/src/components/containers/tooltip/Tooltip.md
- packages/es-components/src/components/containers/tooltip/Tooltip.specs.js
- packages/es-components/src/components/containers/tooltip/__snapshots__/Tooltip.specs.js.snap
- Updates tooltips to be shown on click and makes the show on hover optional
- updates tooltip styling and accessibility
- changes popovers to use `react-transition-group`'s `mountOnEnter` and `unmountOnExit` because the amount of transitions occurring when there are a large number of popovers on a page causes a lot of slow down.
- minor fixes to popover positioning in mobile
- general cleanup
> Updates to Tooltips and tweaks for popover performance

- lerna.json
- packages/es-components-via-theme/package.json
- packages/es-components-wtw-theme/package.json
- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/src/components/containers/drawer/__snapshots__/Drawer.specs.js.snap
- packages/es-components/src/components/controls/checkbox/__snapshots__/Checkbox.specs.js.snap
- packages/es-components/src/components/controls/radio-buttons/__snapshots__/RadioButton.specs.js.snap
Removes reliance on hoek 4.2.0 which was causing a security vulnerability warning.
> Jest Update

- lerna.json
- packages/es-components-via-theme/package.json
- packages/es-components-wtw-theme/package.json
- packages/es-components/package.json
- packages/es-components/src/components/controls/buttons/DropdownButton.js
This PR adds code to set focus on the trigger button when the DropdownButton component closes. This addresses some usability and accessibility concerns.
> Button dropdown

- lerna.json
- packages/es-components-via-theme/index.js
- packages/es-components-via-theme/package.json
- packages/es-components-wtw-theme/index.js
- packages/es-components-wtw-theme/package.json
- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/src/components/containers/fieldset/Fieldset.js
- packages/es-components/src/components/containers/fieldset/Fieldset.specs.js
- packages/es-components/src/components/containers/fieldset/__snapshots__/Fieldset.specs.js.snap
- packages/es-components/src/components/controls/radio-buttons/RadioButton.js
- packages/es-components/src/components/controls/radio-buttons/RadioGroup.js
- packages/es-components/src/components/controls/radio-buttons/RadioGroup.md
- packages/es-components/src/components/controls/radio-buttons/RadioGroup.specs.js
- packages/es-components/src/components/controls/radio-buttons/__snapshots__/RadioButton.specs.js.snap
- packages/es-components/src/components/controls/radio-buttons/__snapshots__/RadioGroup.specs.js.snap
- packages/es-components/src/components/patterns/datepicker/datePickerStyles.js
Addresses TW-42794
1) Removed `ariaHide` prop from `RadioButton`. As far as I can tell its only purpose was to hide the reading of the radio labels if the `extraContent` prop was supplied. It didn't make sense to me that including some text above the radio buttons would disable reading the options for screen readers. If there was a specific reason for this please let me know. :)
2) Removed `extraContent` prop from `Fieldset` where it didn't really make sense to have since it was being rendered as a child anyway. It still works the same way when used in `RadioGroup` where it originated.
3) Removed `onClick` and `value` from `RadioButton` props, as they are passed along with any other props provided to the input.
4) Some minor radio CSS clean up
5) Added `checked` attribute to input, …
> Radio Accessibility Fix & Datepicker Color Update

- lerna.json
- packages/es-components-via-theme/package.json
- packages/es-components-wtw-theme/package.json
- packages/es-components/package.json
- packages/es-components/src/components/containers/popover/Popup.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.md
Splits up the `otherProps` into distinct sets to pass along to react-datepicker and Textbox. The datepicker will only receive props that belong to its propTypes, and Textbox will get all the rest.
> Datepicker Prop Fix

- lerna.json
- packages/es-components-via-theme/package.json
- packages/es-components-wtw-theme/package.json
- packages/es-components/README.md
- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/src/components/controls/textbox/Textbox.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.js
Closes #212
On one hand `Textbox` is growing into a mess. On the other, we can finally use `refs` with masked inputs again.
> Remove react-dom as a peerDependency

- packages/es-components/src/components/base/icons/Icon.md
- packages/es-components/src/components/controls/checkbox/Checkbox.js
- packages/es-components/src/components/controls/checkbox/Checkbox.md
- packages/es-components/src/components/controls/radio-buttons/RadioButton.js
- packages/es-components/src/components/controls/radio-buttons/RadioButton.specs.js
- packages/es-components/src/components/controls/radio-buttons/RadioGroup.js
- packages/es-components/src/components/controls/radio-buttons/radio-fill-variables.js
- packages/es-components/src/components/controls/textbox/Textbox.md
- packages/es-components/src/components/theme/Themes.md
- packages/es-components/styleguide.config.js
Updates styles and padding to match UX Toolkit updates. Makes radio & checkbox controls a little easier to use on touch/smaller devices.
Note: Discussed with Geoff C. and it was decided to make the checked styles match the validationState colors. This is not reflected yet on the UX Toolkit.
Also updates some styles in the style guide website so it can actually behave responsively.
> Radio & Checkbox Style Updates

- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/src/components/containers/menu/InlineContext.js
- packages/es-components/src/components/containers/menu/Menu.js
- packages/es-components/src/components/containers/menu/Menu.specs.js
- packages/es-components/src/components/containers/menu/MenuPanel.js
- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/modal/ModalContext.js
- packages/es-components/src/components/containers/modal/ModalHeader.js
- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/containers/tabPanels/TabPanel.js
- packages/es-components/src/components/containers/tooltip/Tooltip.js
- packages/es-components/src/components/controls/buttons/DropdownButton.js
- packages/es-components/src/components/controls/buttons/DropdownButton.specs.js
- packages/es-components/src/components/controls/buttons/ToggleButton.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.specs.js
- packages/es-components/src/components/patterns/incrementer/Incrementer.js
This PR updates the react and react-dom `peerDependency` to `react@next` and `react-dom@next`, respectively. In doing so,  components can now use [hooks](https://reactjs.org/docs/hooks-reference.html) to manage state, manage DOM interactions, and use context objects.
All components that are currently using classes to manage these capabilities have been converted to using the built in hooks in this PR. 
Notice that there are nearly zero changes required for the tests! 😄
> Use hooks where currently applicable

- packages/es-components/.babelrc.js
- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/rollup.config.js
- packages/es-components/src/components/patterns/incrementer/Incrementer.js
- packages/es-components/src/styleguide/ExampleWrapper.js
- packages/es-components/styleguide.config.js
There are two benefits for switching to rollup from the existing babel build
- **A minor reduction in bundle size** - We reduce the package size of our esm build from 170B to 102B. This is minor, but we also save downstream project from additional module lookups
- **Cleaner bundle file** - The major benefit of this change is result of the rollup build. We have a clean block of import statements used across the package. Looking at this result from time to time can give us a better idea of what modules are getting imported and how. From there we can determine if additional cleanup can be done.
I've already gotten one such instance to the latter point.
```js
import PropTypes, { PropTypes as PropTypes$1 } from 'prop-types';
```
A quick look we see that `Incrementer.js` is using `import { …
> Use Rollup For esmodule build

- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/src/components/containers/drawer/Drawer.js
- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/notification/Notification.js
- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/containers/popover/Popup.js
- packages/es-components/src/components/containers/popover/popoverStyles.js
- packages/es-components/src/components/containers/striped-container/StripedContainer.js
- packages/es-components/src/components/controls/buttons/Button.js
- packages/es-components/src/components/controls/buttons/DropdownButton.js
- packages/es-components/src/components/controls/buttons/ToggleButton.js
- packages/es-components/src/components/controls/checkbox/Checkbox.js
- packages/es-components/src/components/controls/dropdown/Dropdown.js
- packages/es-components/src/components/controls/radio-buttons/RadioButton.js
- packages/es-components/src/components/controls/radio-buttons/RadioGroup.js
- packages/es-components/src/components/controls/textbox/Textbox.js
- packages/es-components/src/components/navigation/breadcrumb/Breadcrumb.js
- packages/es-components/src/components/navigation/sidenav/SideNav.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.js
- packages/es-components/src/components/patterns/datepicker/datePickerStyles.js
- packages/es-components/src/components/patterns/incrementer/Incrementer.js
- packages/es-components/src/components/util/useTheme.js
Upgrade checklist per the [migration guide](https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4)
> Styled Components v4

- packages/es-components/styleguide.config.js
For IE11 compatibility, there are some missing features that babel does
not support out of the box. babel-polyfill is a package that fills in
those gaps and allows common ES6 features to work even in IE11.
Add a script tag that points to babel-polyfill to the head of the template
in order to ensure that the polyfill is loaded before all components are
loaded.
> Fix: add babel-polyfill to head

- packages/es-components/src/.eslintrc
- packages/es-components/src/components/containers/notification/LightNotification.js
- packages/es-components/src/components/containers/notification/LightNotification.md
- packages/es-components/src/components/containers/notification/Message.js
- packages/es-components/src/components/containers/notification/MessageNotification.js
- packages/es-components/src/components/containers/notification/MessageNotification.md
- packages/es-components/src/components/containers/notification/Notification.md
- packages/es-components/src/components/containers/notification/Notification.specs.js
- packages/es-components/src/components/containers/notification/useNotification.js
- packages/es-components/src/components/patterns/callToAction/Action.js
- packages/es-components/src/components/patterns/callToAction/CallToAction.js
- packages/es-components/src/components/patterns/callToAction/CallToAction.md
- packages/es-components/src/components/patterns/callToAction/CallToAction.specs.js
- packages/es-components/src/components/patterns/callToAction/LightCallToAction.js
- packages/es-components/src/components/patterns/callToAction/LightCallToAction.md
- packages/es-components/src/components/patterns/callToAction/getCallToActionChildren.js
- packages/es-components/src/index.js
This pull request adds two additional components (`LightNotification` and `MessageNotification`) to live alongside `Notification`.
I extracted the default messaging behaviors into two components: `Message` and `InlineMessage`. This will allow consumers of the `Notification` to be able to choose whether to use it or not without forcing their hand with required props on `Notification`.
I removed the `extraAlert` prop because they aren't really a concern of this library and should be implemented using `children` in a consuming application.
I removed the `callsToAction` prop because are now in the `CallsToAction` and `LightCallToAction` components.
---
This pull request also adds two new components to Patterns for calls to action. There is an `Action` component that can be used within …
> New notifications and Calls To Action

- packages/es-components/src/components/controls/textbox/Textbox.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.md
A couple of small changes that ensure the prepend/append icon containers match the height of the accompanying textbox across browsers (was uneven in IE11).
> Textbox icon height fix

- packages/es-components/src/components/containers/modal/Modal.md
- packages/es-components/src/components/controls/textbox/Textbox.js
- packages/es-components/styleguide.config.js
One more followup fix to textbox. We were setting `box-sizing: border-box` in the styleguide head which made everything look good in the guide, but not necessarily in downstream projects. Removed it from our head so we can spot those in the future, and added it to the textbox.
> Fix: box-sizing on textbox prepend/append

- packages/es-components/src/components/containers/modal/Modal.js
Modal dialog positioning uses `text-align: center`. This caused the contents of the modal to also be centered, which was unintended.
> Fix: modal content now left-aligned

- packages/es-components/src/components/controls/textbox/Textbox.js
The padding of the textbox was changing depending on whether a validation icon was present. This sets it to one width to remove the unexpected resizing.
> Textbox padding

- packages/es-components/src/components/controls/radio-buttons/RadioGroup.js
Simply allows additional props (like onBlur) to be passed down to RadioButton from RadioGroup. Needed by Team 5.
> RadioGroup additional props

- packages/es-components/src/components/containers/tooltip/Tooltip.js
Buttons are `type='submit'` by default. This causes Tooltips to submit forms when clicked.
For more info, see [the `type` attribute descriptions on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Attributes).
> Fix: ensuring Tooltips have type='button'

- packages/es-components/src/components/containers/popover/Popover.js
Very similar to #264, but for Popovers. See #264 for more context.
> Fix: giving Popover triggers/closes type='button'

- packages/es-components/src/components/controls/textbox/Textbox.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.js
There was an issue in IOS browsers where they would apply custom styling that caused icons and text inputs to be different heights.
By adding `-webkit-appearance: none;` we tell the browser not to apply styling based on the operating system's theme ([MDN page with more info](https://developer.mozilla.org/en-US/docs/Web/CSS/appearance)).
While I was making changes I also updated the native datepicker a little. Although I don't think it's an actual issue at the moment, I figured `onBlur` might be an event we want to handle in the future. The change is in a separate commit, so it'll be very easy for me to remove if there is strong opposition against it.
> Preventing browsers from adding custom styling to textboxes

- packages/es-components/src/components/patterns/datepicker/DatePicker.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.specs.js
Previously, when a partial date was passed in the `selectedDate` prop, the `DatePicker` component would error out. This will gracefully handle partial dates if they're passed in.
> Update: accounting for partial string dates in DatePicker

- packages/es-components/src/components/controls/buttons/Button.js
- packages/es-components/src/components/controls/buttons/Button.md
- packages/es-components/src/components/controls/buttons/OutlineButton.js
- packages/es-components/src/components/controls/radio-buttons/RadioButton.js
- packages/es-components/src/components/controls/textbox/Textbox.specs.js
Changed Button and Outline button components to default to `block` at the mobile breakpoint.
Also made a slight tweak to RadioButton so hovering over a checked radio doesn't lighten it.
> NEXT: Mobile block button

- packages/es-components/src/components/patterns/datepicker/datePickerStyles.js
Simple style fix for the navigation arrows when using `showYearDropdown` in the Datepicker. Fixes #291
> Datepicker year dropdown contrast fix

- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/src/components/patterns/datepicker/DatePicker.specs.js
- packages/es-components/src/components/util/useWindowWidth.specs.js
- packages/es-components/src/components/util/withWindowSize.specs.js
* Addresses the recent lodash vulnerability
* Addresses the numerous audit errors from `npm audit`
* Clean up the errors appearing around `act(() => {})` usage from the second `useWindowWidth` test
* Attempt to improve test performance by reducing the amount of redundant `Object.defineProperty` run per-test
> Github/NPM Security Audit and Test Performance Fixes

- packages/es-components/src/components/util/StyleReset.js
`<sup>` and `<sub>` tags were getting the `vertical-align: baseline;` treatment when there defaults should be `super` and `sub` respectively.
> Fix: reset for sub and sup tags

- packages/es-components/src/components/controls/textbox/MaskedTextbox.js
- packages/es-components/src/components/controls/textbox/MaskedTextbox.md
- packages/es-components/src/components/controls/textbox/TextAddons.js
- packages/es-components/src/components/controls/textbox/Textbox.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.js
- packages/es-components/src/components/util/useWindowWidth.specs.js
Reverting `MaskedTextbox` to use most of the `Textbox` guts. I refactored most of the common styled elements out into a shared file, but I'm sure more clever things could be done to get these two components running in a more concise way. Right now I just want them working.
I tried various methods to get new ref usages (createRef, forwardRef, useRef) working with react-text-mask so we don't have the hacky `DateTextbox` in `DatePicker` just to get the `focus()` working, but using the old callback method is the only combination I could find that works.
> Mask & Datepicker fix

- packages/es-components/src/components/containers/popover/Popover.js
Popover buttons were rendering on the left in viewports less than tablet size because there is an automatic 'display: block' that aligns it to the left. Setting display to auto allows the button to be aligned to the right by inheriting the text-align: right property.
See [this codepen](https://codepen.io/jacobrios/pen/zbwmJZ) for an example of this at work.
> Fix: set popover buttons to display: auto

- packages/es-components/src/components/containers/notification/Notification.md
- packages/es-components/src/components/containers/notification/useNotification.js
Tweaked icon and dismiss alignment within notifications. 
1) Dismiss button should no longer wrap under text when in narrow mobile breakpoints.
2) Dismiss button now uses the variant textColor so it can be seen on whatever background or variant is in use.
> Notification styles

- packages/es-components/src/components/containers/tooltip/Tooltip.js
Fixes a minor issue with tooltip underline behavior on hover and the overlay close behavior when clicking outside of the tooltip
> Fixes for tooltips

- packages/es-components/src/components/containers/modal/Modal.md
- packages/es-components/src/components/containers/modal/ModalHeader.js
- packages/es-components/src/components/containers/modal/__snapshots__/Modal.specs.js.snap
Having the `h4` tag was creating rigidity in the heading levels that raised accessibility concerns in downstream consumers. This fix utilizes [the `Heading` component](https://github.com/WTW-IM/es-components/blob/master/packages/es-components/src/components/containers/heading/Heading.js) to allow us to set whatever heading level we want, without changing the look of the modal header.
> Fix: modal header level accessibility

- packages/es-components/src/components/patterns/incrementer/Incrementer.js
- packages/es-components/src/components/patterns/incrementer/Incrementer.md
- packages/es-components/src/components/patterns/incrementer/Incrementer.specs.js
- Input type is number, so mobile users will get the numeric keyboard
- The increment/decrement amounts now respect the thresholds.
- Using Kent Dodds' preferred (for now?) method of [testing useEffect](https://github.com/kentcdodds/react-testing-library/issues/215#issuecomment-438294336).
- Switched from lodash's `IsNumber` to `IsFinite`, which handles `NaN` in a falsey way.
> Incrementer manual input support

- packages/es-components/src/components/containers/notification/LightNotification.md
- packages/es-components/src/components/containers/notification/Message.js
- packages/es-components/src/components/containers/notification/Notification.md
- packages/es-components/src/components/containers/notification/useNotification.js
- packages/es-components/src/components/controls/Control.js
- `Notification` was updated to use spans rather than paragraph tags to prevent too much padding. 
- `LightNotification` icon colors updated to use the correct associated validation type color to conform to BDA toolkit.
- `Control` bottom margin increased to 25px.
> Notification, Control minor style updates

- packages/es-components/src/components/containers/tooltip/Tooltip.js
- packages/es-components/src/components/controls/buttons/PopoverLink.js
After a discussion with our UX team it has been decided that using this approach is desirable even as it does not fully work with IE. It makes sure that even with wrapped words the underline behaves correctly.
> Update: changes Tooltip/Popover links to use text-decoration-style

- packages/es-components/src/components/containers/notification/useNotification.js
The `initial` css value isn't supported in IE11 (https://caniuse.com/#feat=css-initial-value). This change replaces `initial` with the `<i>` element's default display value of `inline` for the `Notification` component.
> Fix Notification Icons in IE11

- packages/es-components/src/components/controls/buttons/Button.js
In IE11 the Button component's box shadow was being cut off by the parent element. Here's what it looked like:
Convenient arrow in case you couldn't spot the button... 😄 
The fix is to allow `overflow` to be visible on the parent element of the box shadow'd element.
> Fix: Button box shadows cut off in IE11

- packages/es-components/src/components/containers/checkboxLabel/CheckboxLabel.md
- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/notification/Notification.md
- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/controls/checkbox/Checkbox.js
- packages/es-components/src/components/controls/label/Label.js
Allows modals to scroll when their content goes offscreen.
Removed the `display: flex` from `Label` which I think was a holdover from our earlier iteration as it doesn't seem to affect anything.
Fixed an issue where popover links within labels were not activating in Safari.
> Modal scrolling

- packages/es-components/src/components/containers/modal/ModalFooter.js
- packages/es-components/src/components/containers/modal/ModalHeader.js
- packages/es-components/src/components/containers/modal/__snapshots__/Modal.specs.js.snap
Another small tweak that adds some padding to the bottom of the mobile full-screen modal to accommodate the Safari toolbar.
> Fix: modal close button in Safari

- packages/es-components/src/components/containers/heading/Heading.js
- packages/es-components/src/components/containers/heading/Heading.md
- packages/es-components/src/components/containers/heading/Heading.specs.js
- packages/es-components/src/components/containers/heading/__snapshots__/Heading.specs.js.snap
- packages/es-components/src/components/containers/modal/__snapshots__/Modal.specs.js.snap
- packages/es-components/src/components/controls/checkbox/Checkbox.js
- packages/es-components/src/components/controls/radio-buttons/RadioButton.js
- packages/es-components/src/components/util/StyleReset.js
H1 & H2 will size down a bit on mobile now, so teams don't have to write their own media queries.
UX has reviewed and suggested the underlineColor prop to keep it somewhat open to customization.
Also updated Checkbox and Radio labels to use normal font-weight.
> Update: heading styles, added knockout and underlineColor props

- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/modal/ModalFooter.js
- packages/es-components/src/components/containers/modal/__snapshots__/Modal.specs.js.snap
Modal scroll better matches the BDA toolkit and this *should* really fix the mobile Safari issue this time (buttons in footer not able to be pressed due to browser toolbar popping up over it).
Eventually need to add another transition effect for translate in addition the existing `Fade`.
> Fix: modal display to better match BDA toolkit

- packages/es-components/src/components/controls/label/Label.js
This conforms to the styles from the [BDA Style Guide](http://prototypes-wtw.net/controls/#forms-example).
> Fix: ensuring all layout spacing takes effect for labels

- packages/es-components/src/components/containers/notification/useNotification.js
- packages/es-components/src/components/controls/buttons/Button.js
- packages/es-components/src/components/controls/buttons/LinkButton.js
- packages/es-components/src/components/controls/buttons/OutlineButton.js
- packages/es-components/src/components/controls/buttons/PopoverLink.js
- packages/es-components/src/components/controls/textbox/MaskedTextbox.js
- packages/es-components/src/components/controls/textbox/TextAddons.js
- packages/es-components/src/components/controls/textbox/Textbox.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.js
- UX wanted the Textbox append/prepends to be clickable so they focus on the input
- Significantly cleaned up MaskedTextbox code (backwards compatible)
- Changed usage of forwardRef to named functions for better debugging messages. If you forgot to supply a required prop, for example
- before: "The prop 'x' is marked as required in ForwardRef, but its value is undefined."
- after: "The prop 'x' is marked as required in ForwardRef(ComponentName), but its value is undefined."
> Update: Textbox addons focus on click, MaskedTextbox cleanup

- packages/es-components/src/components/containers/menu/MenuPanel.js
- packages/es-components/src/components/containers/modal/Modal.md
- packages/es-components/src/components/containers/modal/ModalHeader.js
- packages/es-components/src/components/containers/modal/__snapshots__/Modal.specs.js.snap
- packages/es-components/src/components/containers/notification/useNotification.js
- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/containers/popover/Popover.md
- packages/es-components/src/components/controls/DismissButton.js
- packages/es-components/src/components/controls/buttons/OutlineButton.js
- packages/es-components/src/components/controls/radio-buttons/RadioButton.js
- packages/es-components/src/components/patterns/dateInput/DateInput.md
1. Made `Popover` `title` not required. 
2. Consistent use of `DismissButton` across `Popover`, `ModalHeader`, `Menu`, and `Notification`.
3. Small style changes to `Popover` text color, `RadioButton` (no bottom margin on last button).
4. Added `DateInput` example with `monthNames`.
5. Fixed OutlineButton width: initial issue. Changed to width: auto. #339
> Update: Popover title not required, DismissButton consistent styles 

- packages/es-components/src/components/controls/radio-buttons/RadioButton.js
quick fix for radio button margins when displayed inline
> Fix: radio buttons uneven inline

- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/containers/popover/Popup.js
Moves `RootCloseWrapper` out of `Popup.js` and into `Popover.js` to fix the issue where clicking inside the popover element would cause the popover to close.
> Fix: fixes popover close behavior after clicking inside element

- packages/es-components/src/components/controls/Control.js
- packages/es-components/src/components/controls/answer-group/AnswerButton.js
- packages/es-components/src/components/controls/answer-group/AnswerGroup.js
AnswerGroup breakpoint from full-width to min-width should be at tablet, not desktop.
Also fixed an inline Control alignment issue.
> Fix: answerGroup media query update

- packages/es-components/src/components/containers/modal/Modal.md
- packages/es-components/src/components/containers/modal/ModalButtonContainer.js
I was talking with Tim this morning and he stated that modal call to action buttons on mobile should span the width of the modal, minus padding of course. It felt best to fix that at the modal level instead inside individual modals, but let me know if anyone disagrees and feels we shouldn't be dictating that for every modal.
> Fix: modal buttons should expand the width of the modal on mobile

- packages/es-components-via-theme/index.js
- packages/es-components-wtw-theme/index.js
- packages/es-components/src/components/controls/buttons/LinkButton.md
Add new inherited button style type. This will allow buttons to inherit colors from its closest parent. This is typically only going to be useful for link buttons.
> New: add inherited button style type

- packages/es-components-via-theme/index.js
- packages/es-components-wtw-theme/index.js
- packages/es-components/src/components/controls/buttons/LinkButton.js
- packages/es-components/src/components/controls/buttons/LinkButton.md
- packages/es-components/src/components/controls/buttons/PopoverLink.js
Trying to manage use the button styles for both links and button links has caused headaches downstream. Make the button link styles a first class citizen.
> New: create a new button style object for link buttons

- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/src/components/patterns/datepicker/DatePicker.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.md
Use the alpha version of date-fns in the DatePicker. There were some confusing bits in the datepicker code that I hope I made a bit more clear. I also got rid of all the props that are only pass throughs to ReactDatePicker.
> Upgrade: use date-fns@next in DatePicker

- packages/es-components/src/components/patterns/dateInput/DateInput.js
- packages/es-components/src/components/patterns/dateInput/DateInput.md
- packages/es-components/src/components/patterns/dateInput/Month.js
Adds a new prop to Month to insert a "select a month" option into the dropdown. This forces the user to actually select an option rather than skipping it and leaving it on the default January option.
Addresses WE-5091
> Update: added selectOptionText prop to DateInput

- packages/es-components/src/components/base/icons/Icon.js
- packages/es-components/src/components/base/icons/Icon.md
- packages/es-components/src/components/containers/heading/Heading.js
- packages/es-components/src/components/containers/heading/__snapshots__/Heading.specs.js.snap
- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/modal/ModalHeader.js
- packages/es-components/src/components/containers/modal/__snapshots__/Modal.specs.js.snap
- packages/es-components/src/components/containers/tooltip/Tooltip.js
- packages/es-components/src/components/controls/label/Label.js
- packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap
- packages/es-components/src/components/theme/Themes.md
- packages/es-components/src/components/util/StyleReset.js
- packages/es-components/styleguide.config.js
Our asset CDN has been set up on a new Azure endpoint, so we need to update our references. I also added the Source Sans Pro font to our CDN so we can exactly match the BDA Toolkit, as the Google-hosted one was a little different (it used the regular variant for bold and light).
We'll need to update other projects with the new CDN URL as well.
> Update: CDN links, font references

- packages/es-components/src/components/containers/heading/Heading.js
- packages/es-components/src/components/containers/heading/__snapshots__/Heading.specs.js.snap
- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/modal/__snapshots__/Modal.specs.js.snap
- packages/es-components/src/components/containers/table/ResponsiveTable.js
- packages/es-components/src/components/containers/table/Table.js
- packages/es-components/src/components/containers/tooltip/Tooltip.js
- packages/es-components/src/components/controls/checkbox/Checkbox.js
- packages/es-components/src/components/controls/label/Label.js
- packages/es-components/src/components/controls/radio-buttons/RadioButton.js
- packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap
- packages/es-components/src/components/util/StyleReset.js
The previous issues with bold rendering in Firefox came from the CDN font source being split into 3 different families (one for regular, light, and bold). That has been fixed and the specific overrides are no longer necessary. Everything just uses 'Source Sans Pro' now and it works as it should. This should also be fully backward compatible with the google Source Sans Pro.
> Unified Source Sans Pro fix

- packages/es-components/src/components/containers/drawer/Drawer.js
This will ensure that doing something like:
{false && <Drawer.Panel>STUFF</Drawer.Panel>} does not throw an exception when trying to conditional render drawer panels.
> Fix: allow null to be used for Drawer children

- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/rollup.config.js
During the switch to rollup, the `browser` field was added to the package.json, pointing to the UMD build (which existed before). Due to the issues caused by webpack preferring this build by default, this simply removes that field from the package.json, while still leaving the UMD build in place as it was before.
Question: Do we still need to have a UMD build?
> Build: removed browser field in package.json

- packages/es-components/src/components/controls/buttons/Button.js
- packages/es-components/src/components/controls/buttons/OutlineButton.js
Explicitly set text-decoration to none so that a Button can be used as a link without it receiving the default browser link treatment.
This will have no outward effects on any existing button styles since text inside them don't get underlined by browsers.
> Fix: set text-decoration on Button

- packages/es-components/src/components/containers/popover/Popover.js
- Because the RootCloseWrapper was around the Popup element instead of
the content of the Popover the onClose would trigger even when clicking
inside of the Popover which is not correct behavior for this type of
element. Moving the wrapper down around the content ensure the close
trigger is fired at the appropriate time.
> Fix: moves RootCloseWrapper in Popover

- packages/es-components/src/components/util/withWindowSize.js
- Adds check in the resize event of withWindowSize that will cause the
new window size to be set on the state when thie active element is
an input or select tag.
- This was added to get around how android browsers resize the viewport
when the 'soft' keyboard is opening, which would cause a rerender and
posibly break things in downstream responsive apps.
> Update: restrict resize event firing

- packages/es-components/src/components/patterns/dateInput/Day.js
- packages/es-components/src/components/patterns/dateInput/Year.js
- packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap
Added `inputmode` and `pattern` attributes to set mobile keyboards to display numeric input when using components.
> Add `inputmode` and `pattern` to Day and Year input components

- packages/es-components/src/components/containers/notification/useNotification.js
We are trying to pass `aria` attributes to a `LightNotification` component.  `Notification` is assigned a `role` attribute, which means that it should also get any passed-in `aria` attributes, but in `useNotification`, any additional props are instead passed on to `NotificationContent`, which is a separate element.  `NotificationContent` also ignores any additional props, so there are really two problems here.  
This PR moves `role` and any additional props to `ContentWrapper` inside of `NotificationContent`.
> pass additional props to Notification components

- packages/es-components/package-lock.json
- packages/es-components/src/components/patterns/dateInput/DateInput.js
- packages/es-components/src/components/patterns/dateInput/DateInput.md
- packages/es-components/src/components/patterns/dateInput/DateInput.specs.js
When specifying selectOptionText for DateInput.Month we should get a none value, but currently we default the month to a value of 1. This allows validation to be successful even when not changing month value.
> Fix: stop default month from being set in DateInput

- packages/es-components/src/components/controls/radio-buttons/RadioButton.js
Fix for bug with the radio button inputs when using the selectedValue in the RadioGroup component, when having an external function set the value of the of the selected element, trying to click the previously selected element won't work
> Fix: pass checked attributed to input element

- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/sliding-pane/SlidingPane.js
Make sure that the modal classes are nested so that it should prevent collisions with the sliding pane.
> Fix: nest styles to prevent css collisions

- packages/es-components/src/components/containers/notification/Notification.specs.js
- packages/es-components/src/components/containers/notification/useNotification.js
This should allow us to use `<Notification style={...}>` and `styled(Notification)` without issues.
> Fix: utilizing upstream styles and classes in Notifications

- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/containers/popover/Popup.js
This will allow downstream projects to enable and disable events. It would be nice to update react-popper so we could have more control over disabling just the scroll or resize events.
> Enable events prop

- packages/es-components/babel.config.js
- packages/es-components/package.json
- packages/es-components/rollup.config.js
This only takes effect in the UMD build.
> Update: removing PropTypes as global dependency

- packages/es-components/src/components/containers/modal/Modal.js
When there are multiple modals on a page, it renders each one on the page. After a certain point, performance degrades and pages become less responsive.
Only rendering if the show prop is true will prevent every modal from being rendered and only render one modal on the page at any given time.
> Update: only render modal if it should show

- packages/es-components/src/components/controls/buttons/Button.js
- packages/es-components/src/components/controls/buttons/Button.md
- packages/es-components/src/components/controls/buttons/DropdownButton.js
- packages/es-components/src/components/controls/buttons/DropdownButton.md
Added `flatLeftEdge` and `flatRightEdge` props to `Button` and `DropdownButton` which enables a `SplitButton` style combination, among other possibilities. The content of the dropdown items will probably need some manual styling (shown in the example added to the .md file) so they are wide enough.
> Button/DropdownButton flatEdge props

- packages/es-components/package.json
This will ensure that the docs build works properly.
> Build: ensuring that the docs folder exists when styleguide build runs

- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/sliding-pane/SlidingPane.js
- packages/es-components/src/components/util/useRootNode.js
I've checked within a regular `document.body` and also within a Web Component, and it seems that this solution does work.
> Update: allow Modals to be used in Web Components without an extra ref

- packages/es-components/src/components/controls/buttons/ToggleButton.js
ToggleButton now properly applies custom `className` prop values, includes those passed by styled-components.
> Fix: classNames properly applied to ToggleButton

- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/modal/Modal.specs.js
styled-components adds classnames for e.g. `const MyModal = styled(Modal)`.  This fix passes class names through to the modal.
> Fix: pass class names through to modal

- packages/es-components/src/components/base/icons/icon-definitions.js
This update adds the `.reply-arrow` icon definition to match the update to `es-assets`, per request from BO-UX.
> UPDATE: Adding icon definition for reply-arrow.

- packages/es-components/src/components/controls/buttons/PopoverLink.js
`border-bottom` doesn't work with wrapped text
Updated to use `text-decoration`
> Fix: use text-decoration for PopoverLink

- packages/es-components/config/styleguidist-page-scripts.js
- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/modal/Modal.md
- packages/es-components/src/components/containers/modal/ModalBody.js
- packages/es-components/src/components/containers/modal/ModalHeader.js
- packages/es-components/src/components/containers/modal/__snapshots__/Modal.specs.js.snap
- packages/es-components/src/components/controls/textbox/TextAddons.js
- packages/es-components/src/components/controls/textbox/Textbox.js
- packages/es-components/styleguide.config.js
This is a large rework of Modals that resolves #471.
Modals now:
* Scroll within themselves in full-width (mobile) view with a fixed header
* Position themselves with their center at about 1/3 down the page.
* Animate correctly
* Scroll within themselves when they are at 100% of the window height (without a fixed header when not in full-width view)
> Fix Modal Scrolling

- packages/es-components/src/components/containers/drawer/Drawer.md
- packages/es-components/src/components/containers/drawer/DrawerPanel.js
from https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA12.html
> If there is more than one heading on the page and the heading hierarchy is defined through the visual presentation, the aria-level attribute should be used to indicate the hierarchical level of the heading.
> New: add heading level to Drawer

- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/sliding-pane/SlidingPane.js
- packages/es-components/src/components/util/useDisableBodyScroll.js
@stevematney I've noticed that this effect is running initially when `Modal`/`SlidingPane` is rendered with `isOpen`/`show` set to false. In that case it just tries to remove that style when it's not there anyway. Not a big problem on one hand but still it bugs me that it's doing what it really shouldn't do. Should I prevent such behavior?
> Update: extract and reuse useDisableBodyScroll

- packages/es-components/src/components/patterns/dateInput/DateInput.js
- packages/es-components/src/components/patterns/dateInput/DateInput.specs.js
Added `rawValues` object to the `DateInput` return object so additional logic/validation can be performed if necessary.
> Update: added rawValues to DateInput return object

- packages/es-components/src/components/controls/dropdown/Dropdown.js
- packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap
The Dropwdown wrapper was unnecessary, and broke when if downstream users passed refs.
> Unwrapping Dropdown

- packages/es-components/src/components/controls/buttons/Button.js
Taking out the role of the combobox ended up breaking it, so I'm going to leave the accessibility fixes for another PR.  This change just adds a border to buttons when they are in focus.
> Update: (WE-11421) add border to button in focus

- packages/es-components/src/components/controls/buttons/Button.js
- packages/es-components/src/components/controls/buttons/ButtonBase.js
- packages/es-components/src/components/controls/buttons/features/withLoadingStateWhileRunning.js
We've started seeing an error pop up in the console:
```console
Cannot read property 'apply' of undefined
```
I think this should fix it, since @sviridovdy narrowed it down to #518, but it's difficult to test without being able to load the UMD module directly. I did pack this up in production mode and I tested it locally. However, the local instance uses the es6 module build and not the UMD build. Even so, I didn't see any errors.
I can at least say that this change does not break anything.
> Fix: ensuring we don't spread over potentially undefined propTypes

- packages/es-components/src/components/controls/dropdown/Dropdown.js
Previously if a `Dropdown` wasn't wrapped in a `Control` it would not set the focus styles correctly. This applies the default focus styles from the theme if the values aren't supplied via other methods.
> Fix: set Dropdown focus values if validation context not available

- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/containers/popover/Popover.md
- packages/es-components/src/components/containers/popover/Popup.js
This is a pretty simple update. We're just passing through extra props. The need for this stemmed from a problem I ran into where I needed to be able to lower the `min-width` of the popup container.
> Allow popovers to have custom styling

- packages/es-components/src/components/util/isParseableDate.js
The error stems from how require works. If a module is not found at the current directory it'll keep going up until it either finds one that matches or throws if we finally hit global and it does not exist. `date-fns/is_valid` does not exist in `date-fns@2.4.1` that is referenced in `es-components`, but the module does exist in `date-fns@1.30.1` that is used by out of our indirect dependencies in the project root.
> Fix: use correct date-fns isValid import

- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/containers/popover/Popover.md
* A custom proptype is used to ensure either `content` or `renderContent` is used
> New: provide render function for popover content body

- packages/es-components/src/components/containers/popover/Popover.js
Calling `PropTypes.node` and `PropTypes.func` from within the custom validator was throwing console errors.
> Fix: prevent unnecesary proptypes warnings

- packages/es-components/src/components/containers/sliding-pane/SlidingPane.js
Sometimes it is desired to pass a width to the sliding pane. Add a
prop that will allow this to be passed and if it is null, default
it to the tablet size.
> Update: allow width passed to sliding pane

- packages/es-components/src/components/containers/heading/Heading.js
- packages/es-components/src/components/containers/heading/__snapshots__/Heading.specs.js.snap
- packages/es-components/src/components/containers/modal/__snapshots__/Modal.specs.js.snap
This simplification may not seem necessary, but exporting the Styled Component without wrapping it in another component allows for things downstream like this:
```jsx
import { Heading } from 'es-components';
const MySpecialContainer = styled.div`
background-color: papayawhip;
${Heading} {
color: rebeccapurple;
}
`;
```
*Note*: Targeting master directly as this does not change anything external to the Headings. I will deploy a canary to test.
> Exporting Headings as a styled component

- packages/es-components/src/components/containers/horizontalScrollWrapper/HorizontalScrollWrapper.js
Related bug: https://jira.extendhealth.com/browse/WE-14049
> Fix: suppress uncaught error if element is not loaded

- package-lock.json
- package.json
- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/src/components/base/icons/Icon.js
- packages/es-components/src/components/base/icons/IconContext.js
This also includes some work to optimize across es-components instances on a page. We'll always set up the icon font on the document, but only once. This ensures that if nothing else on the page is rendering icons besides Web Components, the icons will still appear.
Fonts can be used inside a Web Component, but they must also exist on the Document. It's a weird limitation of Web Components, [as described in this bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=336876).
> Fix: ensuring that we always initialize icons on the body

- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/containers/popover/Popover.md
This PR adds two things:
1. A `styleType` prop to the Popover component so that it can easily match the `styleType` of its triggering Button
2. A `popoverWrapperClassName` prop to Popover so active popovers can be queried on the DOM
In hindsight, item 1 could have been easily solved downstream with styled components. I'm a bit new to the React component world and didn't realize that until I'd made these changes. Hopefully this still makes the Popover more convenient to work with.
> CPED-1875 Small Popver Addition

- packages/es-components/src/components/util/StyleReset.js
- packages/es-components/styleguide.config.js
The overflow style was causing some unintended side-effects in the Datepicker component. I'm not sure why it was part of it to begin with, and the rest of the components behave the same without it, so I'm just removing it.
> Fix: removed overflow clip from global focus style

- packages/es-components-via-theme/index.js
- packages/es-components/src/components/controls/textbox/InputBase.js
- packages/es-components/src/components/controls/textbox/Textarea.js
- packages/es-components/src/components/patterns/dateInput/__snapshots__/DateInput.specs.js.snap
> Update(styling): WE-16644 consistent font for text inputs and areas & consistent spacing

- .npmrc
- package-lock.json
- package.json
- packages/es-components/.npmrc
- packages/es-components/package-lock.json
- packages/es-components/src/components/controls/switch/Switch.js
- packages/es-components/src/components/controls/switch/Switch.specs.js
In scenarios where a Switch component's `isToggled` state is controlled externally changing `checked` does not update the switch visually due to `defaultChecked` ignoring subsequent renders.
> Fix: resync checked prop with checked for Switch's underlying checkbox input

- package.json
- packages/es-components-wtw-theme/package-lock.json
- packages/es-components/.eslintrc.js
- packages/es-components/package-lock.json
- packages/es-components/package.json
- packages/es-components/src/components/containers/popover/Popover.js
a. Remove conditional based on react version that determines whether e.stopPropagation is called in toggleShow of popover.
b. add cross-env for build command so we can run prepublishOnly on Windows.
c. Update precommit hook so we can make a commit on Windows.
> Fix popover

- packages/es-components/src/components/containers/popover/Popover.js
- packages/es-components/src/components/containers/popover/Popover.specs.js
Previously, the focus would land on the closing instruction span and would look like this:
Now, focus will land on the Popover content and look like this
> Update: focusing popover content when opened, rather than esc links

- .github/workflows/commit-lint.yml
- packages/es-components/src/components/util/StyleReset.js
`:focus-visible` matches the browser's logic around when a focus style should be shown instead of overriding that logic as regular `:focus` does.
See: [this article about the differences between :focus-visible and :focus](https://pawelgrzybek.com/the-difference-between-css-focus-and-focus-visible-pseudo-class/#:~:text=Adding%20the%20%3Afocus%20pseudo%2Dclass,research%20in%20one%20CSS%20property.)
> New: using :focus-visible instead of :focus for global focus styles

- packages/es-components/src/components/containers/menu/MenuPanel.js
- packages/es-components/src/components/containers/modal/Modal.js
- packages/es-components/src/components/containers/popover/Popup.js
- packages/es-components/src/components/containers/tooltip/Tooltip.js
- packages/es-components/src/components/controls/buttons/DropdownButton.js
- packages/es-components/src/components/patterns/datepicker/DatePicker.js
- packages/es-components/src/components/patterns/datepicker/datePickerStyles.js
- packages/es-components/src/hooks/useTopZIndex.js
[WE-18942](https://jira.extendhealth.com/browse/WE-18942) - Shopping - The dropdown in Plan Rec sits behind the Shopping Plan Compare Component.
On this bug, the household dropdown is displaying behind the Shopping Plan Compare web component. So, I adjusted the z-index a bit, in hopes to fix this issue.
Area's I've tested
- Toast notifications. I've tested toast notifications which appears that the z-index is set to 1001. 
- Via Benefits banner. I've tested Via Benefits banner which appears that the z-index is set to 1005. 
- Shopping Plan Compare web component. I've tested the Shopping Plan Compare web component header which appears that the z-index is set to 999. 
I also tested other area's such as modals and sliding panes within plan recommendation. 
- Health Information sliding pane …
> WE-18942 Bumped z-index in order to fix an overlap bug
